spring:
  kafka:
    consumer:
      group-id: demo
      auto-offset-reset: latest
#      bootstrap-servers: 172.16.102.23:9092
      bootstrap-servers: 11.11.1.108:9092
      client-id: consumer-1
    producer:
#      bootstrap-servers: 172.16.102.23:9092
      bootstrap-servers: 11.11.1.108:9092
      client-id: producer-1